/**
 * Application Error Codes
 * Structured error codes for programmatic error identification.
 * Format: MODULE_NNN
 */

const ERROR_CODES = {
  // Authentication errors (AUTH_0xx)
  AUTH_TOKEN_MISSING: 'AUTH_001',
  AUTH_TOKEN_INVALID: 'AUTH_002',
  AUTH_TOKEN_EXPIRED: 'AUTH_003',
  AUTH_REFRESH_INVALID: 'AUTH_004',
  AUTH_INSUFFICIENT_ROLE: 'AUTH_005',
  AUTH_ACCOUNT_DISABLED: 'AUTH_006',
  AUTH_OTP_INVALID: 'AUTH_007',
  AUTH_OTP_EXPIRED: 'AUTH_008',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_009',

  // Validation errors (VAL_0xx)
  VALIDATION_FAILED: 'VAL_001',
  VALIDATION_FIELD_REQUIRED: 'VAL_002',
  VALIDATION_FIELD_INVALID: 'VAL_003',

  // Resource errors (RES_0xx)
  RESOURCE_NOT_FOUND: 'RES_001',
  RESOURCE_ALREADY_EXISTS: 'RES_002',
  RESOURCE_CONFLICT: 'RES_003',

  // File & upload errors (FILE_0xx)
  FILE_UPLOAD_FAILED: 'FILE_001',
  FILE_TOO_LARGE: 'FILE_002',
  FILE_TYPE_NOT_ALLOWED: 'FILE_003',
  FILE_NOT_FOUND: 'FILE_004',

  // Database errors (DB_0xx)
  DB_CONNECTION_FAILED: 'DB_001',
  DB_QUERY_FAILED: 'DB_002',
  DB_TRANSACTION_FAILED: 'DB_003',

  // External service errors (EXT_0xx)
  EXT_SERVICE_UNAVAILABLE: 'EXT_001',
  EXT_BHASHINI_FAILED: 'EXT_002',
  EXT_SMS_FAILED: 'EXT_003',
  EXT_EMAIL_FAILED: 'EXT_004',
  EXT_S3_FAILED: 'EXT_005',
  EXT_KMS_FAILED: 'EXT_006',
  EXT_WEATHER_FAILED: 'EXT_007',
  EXT_MANDI_FAILED: 'EXT_008',

  // Rate limiting (RATE_0xx)
  RATE_LIMIT_EXCEEDED: 'RATE_001',

  // Server errors (SRV_0xx)
  SERVER_INTERNAL_ERROR: 'SRV_001',
  SERVER_NOT_IMPLEMENTED: 'SRV_002',
};

module.exports = ERROR_CODES;
