/** i18n fragment: kcc screens. Keys are "namespace.key" → { en, hi }. */
const frag: Record<string, { en: string; hi: string }> = {
  // ── kcc-limit: workflow steps ──
  "kcc.step.calculate": { en: "Calculate your limit", hi: "अपनी सीमा जानें" },
  "kcc.step.become_member": { en: "Become a society member", hi: "समिति के सदस्य बनें" },
  "kcc.step.fill_submit": { en: "Fill & submit the KCC form", hi: "केसीसी फॉर्म भरें और जमा करें" },
  "kcc.step.secretary_helps": { en: "Secretary / Bank Mitra helps fill the form", hi: "सचिव / बैंक मित्र फॉर्म भरने में मदद करते हैं" },
  "kcc.step.union_certifies": { en: "Milk Union certifies membership, cattle, milk supply & DBT", hi: "दूध संघ सदस्यता, पशु, दूध आपूर्ति और डीबीटी प्रमाणित करता है" },
  "kcc.step.kyc_verified": { en: "KYC & animal documents verified", hi: "केवाईसी और पशु दस्तावेज़ जाँचे जाते हैं" },
  "kcc.step.limit_fixed": { en: "Loan limit fixed (Scale of Finance)", hi: "ऋण सीमा तय होती है (स्केल ऑफ फाइनेंस)" },
  "kcc.step.forms_to_bank": { en: "Savings account + forms to bank (within 15 days)", hi: "बचत खाता + फॉर्म बैंक को (15 दिन में)" },
  "kcc.step.sanction_disburse": { en: "Sanction & disburse to your account", hi: "स्वीकृति और आपके खाते में राशि" },
  "kcc.step.ongoing_repay": { en: "Milk DBT repays · prompt repayment → 3% subvention", hi: "दूध डीबीटी से चुकौती · समय पर चुकौती → 3% छूट" },

  // ── kcc-limit: actor labels ──
  "kcc.actor.you": { en: "You", hi: "आप" },
  "kcc.actor.society": { en: "Society / Milk Union", hi: "समिति / दूध संघ" },
  "kcc.actor.bank": { en: "Bank (DCCB)", hi: "बैंक (डीसीसीबी)" },
  "kcc.actor.ongoing": { en: "Ongoing", hi: "जारी" },

  // ── kcc-limit: alerts & home ──
  "kcc.submitted_title": { en: "Submitted", hi: "जमा हो गया" },
  "kcc.submitted_msg": { en: "Your application is with your society for certification.", hi: "आपका आवेदन प्रमाणन के लिए आपकी समिति के पास है।" },
  "kcc.not_submitted": { en: "Not submitted", hi: "जमा नहीं हुआ" },
  "kcc.cannot_connect": { en: "Cannot connect.", hi: "कनेक्ट नहीं हो पा रहा।" },
  "kcc.title_dairy": { en: "Kisan Credit Card — Dairy", hi: "किसान क्रेडिट कार्ड — डेयरी" },
  "kcc.home_lead": { en: "Credit built from your herd and your milk record — routed through your society, no forms at the bank.", hi: "आपके पशुओं और दूध रिकॉर्ड से बना क्रेडिट — आपकी समिति के ज़रिए, बैंक में कोई फॉर्म नहीं।" },
  "kcc.calc_my_limit": { en: "Calculate my limit", hi: "मेरी सीमा जानें" },
  "kcc.calc_sub": { en: "See what you qualify for", hi: "मेरी सीमा जानें" },
  "kcc.apply_kcc": { en: "Apply for KCC", hi: "केसीसी के लिए आवेदन करें" },
  "kcc.apply_sub": { en: "Fill the KCC form", hi: "केसीसी फॉर्म भरें" },
  "kcc.check_eligibility": { en: "Check my eligibility & trust score", hi: "मेरी पात्रता और भरोसा स्कोर देखें" },
  "kcc.how_it_works": { en: "How it works", hi: "यह कैसे काम करता है" },

  // ── kcc-limit: facility view ──
  "kcc.estimated_limit": { en: "Estimated limit", hi: "अनुमानित सीमा" },
  "kcc.sanctioned_limit": { en: "Sanctioned limit", hi: "स्वीकृत सीमा" },
  "kcc.cash_credit_st": { en: "Cash credit (ST)", hi: "नकद ऋण (अल्पकालिक)" },
  "kcc.investment_lt": { en: "Investment (LT)", hi: "निवेश (दीर्घकालिक)" },
  "kcc.collateral_free_upto": { en: "Collateral-free up to", hi: "बिना गारंटी" },
  "kcc.upto_word": { en: "", hi: "तक" },
  "kcc.tieup_ok": { en: " · tie-up ✓", hi: " · टाई-अप ✓" },
  "kcc.tieup_requested": { en: " · tie-up requested", hi: " · टाई-अप अनुरोधित" },
  "kcc.app_progress": { en: "Application progress", hi: "आवेदन की प्रगति" },
  "kcc.submit_to_society": { en: "Submit to my society →", hi: "मेरी समिति को जमा करें →" },
  "kcc.wait_submitted": { en: "⏳ With your society — the Milk Union is certifying your membership, cattle and milk supply.", hi: "⏳ आपकी समिति के पास — दूध संघ आपकी सदस्यता, पशु और दूध आपूर्ति प्रमाणित कर रहा है।" },
  "kcc.wait_certified": { en: "✓ Society certified. Now with the bank for KYC & document verification.", hi: "✓ समिति ने प्रमाणित किया। अब केवाईसी और दस्तावेज़ जाँच के लिए बैंक के पास।" },
  "kcc.wait_bank": { en: "🏦 The bank is processing your application. You'll be notified on sanction.", hi: "🏦 बैंक आपका आवेदन देख रहा है। स्वीकृति पर आपको सूचित किया जाएगा।" },
  "kcc.your_application": { en: "Your application", hi: "आपका आवेदन" },
  "kcc.dbt_account": { en: "DBT account", hi: "डीबीटी खाता" },
  "kcc.milk_union_tieup": { en: "Milk-union tie-up", hi: "दूध संघ टाई-अप" },
  "kcc.tieup_req_value": { en: "Requested (→ ₹3L)", hi: "अनुरोधित (→ ₹3 लाख)" },
  "kcc.no": { en: "No", hi: "नहीं" },
  "kcc.kyc_ready": { en: "KYC ready", hi: "केवाईसी तैयार" },
  "kcc.documents_word": { en: "documents", hi: "दस्तावेज़" },
  "kcc.tripartite": { en: "Tripartite", hi: "त्रिपक्षीय" },
  "kcc.agreed": { en: "Agreed", hi: "सहमत" },
  "kcc.buy_animal_equip": { en: "🐄 Buy an animal / equipment (LT drawdown)", hi: "🐄 पशु / उपकरण खरीदें (दीर्घकालिक निकासी)" },
  "kcc.view_banker_pack": { en: "📄 View banker pack", hi: "📄 बैंकर पैक देखें" },
  "kcc.recalculate": { en: "Re-calculate my limit", hi: "मेरी सीमा फिर से जानें" },

  // ── kcc-apply ──
  "kcc.kyc.aadhaar": { en: "Aadhaar card", hi: "आधार कार्ड" },
  "kcc.kyc.pan": { en: "PAN card", hi: "पैन कार्ड" },
  "kcc.kyc.land": { en: "Land record", hi: "भूमि दस्तावेज़" },
  "kcc.kyc.photo": { en: "Photograph", hi: "फ़ोटो" },
  "kcc.consent_needed": { en: "Consent needed", hi: "सहमति आवश्यक" },
  "kcc.consent_msg": { en: "Please confirm the declaration to apply.", hi: "आवेदन करने के लिए घोषणा की पुष्टि करें।" },
  "kcc.bank_account_title": { en: "Bank account", hi: "बैंक खाता" },
  "kcc.bank_account_msg": { en: "Enter your DCCB / cooperative-bank savings account number for DBT.", hi: "डीबीटी के लिए अपना डीसीसीबी / सहकारी बैंक बचत खाता नंबर दर्ज करें।" },
  "kcc.kyc_docs_title": { en: "KYC documents", hi: "केवाईसी दस्तावेज़" },
  "kcc.kyc_docs_msg": { en: "Please confirm you have all four documents ready — the bank will verify them.", hi: "पुष्टि करें कि चारों दस्तावेज़ तैयार हैं — बैंक इन्हें जाँचेगा।" },
  "kcc.app_saved_title": { en: "Application saved", hi: "आवेदन सहेजा गया" },
  "kcc.app_saved_msg": { en: "Now submit it to your society for certification.", hi: "अब इसे प्रमाणन के लिए अपनी समिति को जमा करें।" },
  "kcc.could_not_apply": { en: "Could not apply", hi: "आवेदन नहीं हो सका" },
  "kcc.join_society_msg": { en: "Join your dairy society first — the KCC is routed through the society.", hi: "पहले अपनी डेयरी समिति से जुड़ें — केसीसी समिति के ज़रिए जाता है।" },
  "kcc.cannot_connect_check": { en: "Cannot connect. Check your connection.", hi: "कनेक्ट नहीं हो पा रहा। अपना कनेक्शन जाँचें।" },
  "kcc.join_first_title": { en: "Join your society first", hi: "पहले अपनी समिति से जुड़ें" },
  "kcc.join_first_msg": { en: "The KCC Dairy loan is routed through your Dairy Cooperative Society / Milk Union. Link your membership to apply.", hi: "केसीसी डेयरी ऋण आपकी डेयरी सहकारी समिति / दूध संघ के ज़रिए जाता है। आवेदन के लिए अपनी सदस्यता जोड़ें।" },
  "kcc.go_to_society": { en: "Go to my society", hi: "मेरी समिति पर जाएँ" },
  "kcc.apply_lead": { en: "Your Secretary or Bank Mitra can help you fill this. The Milk Union certifies it before the bank.", hi: "आपके सचिव या बैंक मित्र इसे भरने में मदद कर सकते हैं। बैंक से पहले दूध संघ इसे प्रमाणित करता है।" },
  "kcc.your_dairy": { en: "Your dairy", hi: "आपकी डेयरी" },
  "kcc.animals_in_kcc": { en: "Animals in this KCC", hi: "इस केसीसी में पशु" },
  "kcc.animals_in_register": { en: "Animals in your register", hi: "आपके रजिस्टर में पशु" },
  "kcc.selected_word": { en: "selected", hi: "चुने गए" },
  "kcc.society_member": { en: "Society member", hi: "समिति सदस्य" },
  "kcc.linked": { en: "✓ Linked", hi: "✓ जुड़ा" },
  "kcc.estimated_limit_sof": { en: "Estimated limit (Scale of Finance)", hi: "अनुमानित सीमा (स्केल ऑफ फाइनेंस)" },
  "kcc.limit_fixed_hint": { en: "Your limit is fixed from the number of animals × the Scale of Finance — not typed by hand.", hi: "आपकी सीमा पशुओं की संख्या × स्केल ऑफ फाइनेंस से तय होती है — हाथ से नहीं भरी जाती।" },
  "kcc.kyc_documents": { en: "KYC documents", hi: "केवाईसी दस्तावेज़" },
  "kcc.kyc_confirm_hint": { en: "Confirm you have these ready — the bank will verify the originals.", hi: "पुष्टि करें कि ये तैयार हैं — बैंक मूल दस्तावेज़ जाँचेगा।" },
  "kcc.bank_for_dbt": { en: "Bank account for DBT", hi: "डीबीटी के लिए बैंक खाता" },
  "kcc.bank_placeholder": { en: "DCCB / cooperative-bank a/c number", hi: "डीसीसीबी / सहकारी बैंक खाता नंबर" },
  "kcc.bank_hint": { en: "Your milk payment (DBT) and the loan are routed through this account.", hi: "आपका दूध भुगतान (डीबीटी) और ऋण इसी खाते के ज़रिए जाते हैं।" },
  "kcc.milk_union_tieup_title": { en: "Milk-union tie-up", hi: "दूध संघ टाई-अप" },
  "kcc.tieup_check": { en: "I supply milk to my Milk Union (tie-up, no intermediary)", hi: "मैं अपने दूध संघ को दूध देता हूँ (टाई-अप, बिना बिचौलिया)" },
  "kcc.tieup_hint": { en: "✓ A tie-up can raise your collateral-free limit to ₹3 lakh (RBI).", hi: "✓ टाई-अप से आपकी बिना गारंटी सीमा ₹3 लाख हो सकती है (आरबीआई)।" },
  "kcc.repay_support": { en: "Repayment support (optional)", hi: "चुकौती सहायता (वैकल्पिक)" },
  "kcc.tripartite_check": { en: "Agree to a tripartite arrangement (me + bank + Milk Union) so milk dues can cover repayment", hi: "त्रिपक्षीय व्यवस्था (मैं + बैंक + दूध संघ) से सहमत हूँ ताकि दूध बकाया से चुकौती हो सके" },
  "kcc.nocost_check": { en: "Opt in to the no-cost service arrangement", hi: "बिना शुल्क सेवा व्यवस्था चुनें" },
  "kcc.repay_hint": { en: "✓ Prompt repayment earns an extra 3% interest subvention and a higher credit limit.", hi: "✓ समय पर चुकौती से अतिरिक्त 3% ब्याज छूट और ज़्यादा ऋण सीमा मिलती है।" },
  "kcc.declaration": { en: "I declare the above is correct and consent to the society/bank verifying it (DPDP).", hi: "मैं घोषित करता हूँ कि ऊपर दी जानकारी सही है और समिति/बैंक द्वारा जाँच की सहमति देता हूँ (डीपीडीपी)।" },
  "kcc.save_application": { en: "Save application", hi: "आवेदन सहेजें" },
  "kcc.apply_footer": { en: "Next: submit to your society → the Milk Union certifies → the bank sanctions and disburses.", hi: "आगे: अपनी समिति को जमा करें → दूध संघ प्रमाणित करता है → बैंक स्वीकृत कर राशि देता है।" },

  // ── kcc-calculator ──
  "kcc.calc_banner": { en: "Your limit is built from your animals on record. Pick which animals to raise the KCC against — sold animals drop out automatically.", hi: "आपकी सीमा रजिस्टर में दर्ज पशुओं से बनती है। चुनें कि किन पशुओं पर केसीसी लेना है — बिके पशु अपने आप हट जाते हैं।" },
  "kcc.your_animals": { en: "Your animals", hi: "आपके पशु" },
  "kcc.sold_confirm_title": { en: "Sold this animal?", hi: "यह पशु बेच दिया?" },
  "kcc.sold_confirm_msg": { en: "will be removed from your herd and drop out of the KCC limit.", hi: "आपके झुंड से हटा दिया जाएगा और केसीसी सीमा से बाहर हो जाएगा।" },
  "kcc.yes_sold": { en: "Yes, sold", hi: "हाँ, बेचा" },
  "kcc.could_not_update": { en: "Could not update", hi: "अपडेट नहीं हो सका" },
  "kcc.no_animals": { en: "No animals on record", hi: "रजिस्टर में कोई पशु नहीं" },
  "kcc.no_animals_msg": { en: "Your KCC limit is built from your animals. Add them to your dairy register first.", hi: "आपकी केसीसी सीमा आपके पशुओं से बनती है। पहले उन्हें अपने डेयरी रजिस्टर में जोड़ें।" },
  "kcc.go_to_animals": { en: "Go to my animals", hi: "मेरे पशुओं पर जाएँ" },
  "kcc.animal_word": { en: "Animal", hi: "पशु" },
  "kcc.value_word": { en: "value", hi: "मूल्य" },
  "kcc.sold_q": { en: "Sold?", hi: "बेचा?" },
  "kcc.units_live_hint": { en: "Units come live from your register — never typed by hand (Scale of Finance ₹7,000/cow).", hi: "इकाइयाँ आपके रजिस्टर से सीधे आती हैं — कभी हाथ से नहीं भरी जातीं (स्केल ऑफ फाइनेंस ₹7,000/गाय)।" },
  "kcc.sold_exited": { en: "Sold / exited — not counted", hi: "बिके / निकले — गिनती में नहीं" },
  "kcc.composite_limit": { en: "Your composite KCC limit", hi: "आपकी संयुक्त केसीसी सीमा" },
  "kcc.animal_one": { en: "animal", hi: "पशु" },
  "kcc.animal_many": { en: "animals", hi: "पशु" },
  "kcc.collateral_free_full": { en: "collateral-free up to ₹2 lakh (₹3 lakh with milk-union tie-up)", hi: "बिना गारंटी ₹2 लाख तक (दूध संघ टाई-अप से ₹3 लाख)" },
  "kcc.six_year_schedule": { en: "6-year schedule (MPL ×1.10 / year)", hi: "6-वर्ष अनुसूची (एमपीएल ×1.10 / वर्ष)" },
  "kcc.year_word": { en: "Year", hi: "वर्ष" },
  "kcc.apply_this_kcc": { en: "Apply for this KCC →", hi: "इस केसीसी के लिए आवेदन करें →" },

  // ── kcc-eligibility ──
  "kcc.trust_score": { en: "Trust score", hi: "भरोसा स्कोर" },
  "kcc.decision_support": { en: "Decision support with reason codes — the sanctioned limit is always the engine's statutory math.", hi: "कारण कोड के साथ निर्णय सहायता — स्वीकृत सीमा हमेशा इंजन की वैधानिक गणना होती है।" },
  "kcc.why": { en: "Why", hi: "क्यों" },
  "kcc.pillars_pending": { en: "Pillars pending (later phases):", hi: "बाकी आधार (आगे के चरण):" },
  "kcc.collateral_ceiling": { en: "Collateral-free ceiling", hi: "बिना गारंटी सीमा" },

  // ── kcc-drawdown ──
  "kcc.item.animal": { en: "🐄 Animal", hi: "🐄 पशु" },
  "kcc.item.shed": { en: "🏚️ Shed", hi: "🏚️ शेड" },
  "kcc.item.equipment": { en: "⚙️ Equipment", hi: "⚙️ उपकरण" },
  "kcc.fill_it_in": { en: "Fill it in", hi: "जानकारी भरें" },
  "kcc.fill_desc_amount": { en: "Add a description and an amount.", hi: "विवरण और राशि जोड़ें।" },
  "kcc.could_not_raise": { en: "Could not raise", hi: "नहीं उठाया जा सका" },
  "kcc.sent_to_bank": { en: "Sent to the bank for approval.", hi: "स्वीकृति के लिए बैंक को भेजा गया।" },
  "kcc.apply_first": { en: "Apply for a KCC first.", hi: "पहले केसीसी के लिए आवेदन करें।" },
  "kcc.investment_headroom": { en: "Investment headroom (LT)", hi: "निवेश गुंजाइश (दीर्घकालिक)" },
  "kcc.of_word": { en: "of", hi: "में से" },
  "kcc.committed_word": { en: "committed", hi: "प्रतिबद्ध" },
  "kcc.new_drawdown": { en: "New drawdown", hi: "नई निकासी" },
  "kcc.desc_placeholder": { en: "Description (e.g., CB cow)", hi: "विवरण (जैसे संकर गाय)" },
  "kcc.amount_placeholder": { en: "Amount (₹)", hi: "राशि (₹)" },
  "kcc.drawdown_note": { en: "📷 Quotation photo/OCR attaches on the next step. On disbursement the asset auto-enters your register + an insurance nudge.", hi: "📷 कोटेशन फोटो/ओसीआर अगले चरण में जुड़ता है। राशि मिलने पर संपत्ति अपने आप आपके रजिस्टर में आती है + बीमा सुझाव।" },
  "kcc.submit_drawdown": { en: "Submit drawdown", hi: "निकासी जमा करें" },
  "kcc.your_drawdowns": { en: "Your drawdowns", hi: "आपकी निकासियाँ" },

  // ── kcc-pack ──
  "kcc.renewal_pack": { en: "Renewal Pack", hi: "नवीनीकरण पैक" },
  "kcc.application_pack": { en: "Application Pack", hi: "आवेदन पैक" },
  "kcc.banker_interface_suffix": { en: "the banker interface", hi: "बैंकर इंटरफ़ेस" },
  "kcc.applicant": { en: "Applicant", hi: "आवेदक" },
  "kcc.name": { en: "Name", hi: "नाम" },
  "kcc.mobile": { en: "Mobile", hi: "मोबाइल" },
  "kcc.composite_mpl": { en: "Composite MPL (CMPL)", hi: "संयुक्त एमपीएल (सीएमपीएल)" },
  "kcc.st_sublimit": { en: "ST sub-limit (cash credit)", hi: "अल्पकालिक उप-सीमा (नकद ऋण)" },
  "kcc.lt_sublimit": { en: "LT sub-limit (investment)", hi: "दीर्घकालिक उप-सीमा (निवेश)" },
  "kcc.sixth_year_mpl": { en: "6th-year MPL", hi: "6ठे वर्ष का एमपीएल" },
  "kcc.collateral_free_label": { en: "Collateral-free", hi: "बिना गारंटी" },
  "kcc.yes_2lakh": { en: "Yes (≤ ₹2 lakh)", hi: "हाँ (≤ ₹2 लाख)" },
  "kcc.activities_title": { en: "Activities (units live from registers)", hi: "गतिविधियाँ (इकाइयाँ रजिस्टर से सीधे)" },
  "kcc.drawing_power_title": { en: "Drawing power (¶16(4) receivables)", hi: "आहरण शक्ति (¶16(4) प्राप्य)" },
  "kcc.drawing_power": { en: "Drawing power", hi: "आहरण शक्ति" },
  "kcc.milk_receivables": { en: "Milk receivables (co-op)", hi: "दूध प्राप्य (सहकारी)" },
  "kcc.stocks": { en: "Stocks", hi: "स्टॉक" },
  "kcc.pack_footer": { en: "Deterministic per RBI KCC Directions 2026. Co-op input credit is NOT part of this limit. Download the full print-ready pack at /kcc/facility/…/pack.html.", hi: "आरबीआई केसीसी निर्देश 2026 के अनुसार निर्धारित। सहकारी इनपुट क्रेडिट इस सीमा का हिस्सा नहीं है। पूरा प्रिंट-तैयार पैक /kcc/facility/…/pack.html पर डाउनलोड करें।" },
};
export default frag;
