/** i18n fragment: dairy screens. Keys are "namespace.key" → { en, hi }. */
const frag: Record<string, { en: string; hi: string }> = {
  // ── activity hubs (dairy / goatery / poultry drill-in) ──
  "dairy.hub.title": { en: "Dairy", hi: "डेयरी" },
  "dairy.hub.sub": { en: "Tap any row below to dive in", hi: "अंदर जाने के लिए नीचे किसी भी पंक्ति पर टैप करें" },
  "dairy.hub.edit_herd": { en: "✏️ Edit herd", hi: "✏️ झुंड बदलें" },
  "dairy.hub.animals": { en: "My animals", hi: "मेरे पशु" },
  "dairy.hub.animals_desc": { en: "List, rename, add, remove individual animals", hi: "पशुओं की सूची, नाम बदलें, जोड़ें, हटाएँ" },
  "dairy.hub.logbook": { en: "Logbook", hi: "बही" },
  "dairy.hub.logbook_desc": { en: "Daily milk, feed, and revenue entries", hi: "रोज़ाना दूध, दाना और आय की प्रविष्टियाँ" },
  "dairy.hub.treatment": { en: "Treatment log", hi: "इलाज बही" },
  "dairy.hub.treatment_desc": { en: "Vaccinations, illness, vet visits", hi: "टीके, बीमारी, पशु-चिकित्सक की जाँच" },
  "dairy.hub.pnl": { en: "P&L", hi: "लाभ-हानि" },
  "dairy.hub.pnl_desc": { en: "Herd profit / loss for the date range", hi: "चुनी अवधि का झुंड लाभ / हानि" },
  "dairy.hub.my_society": { en: "🥛 My Society", hi: "🥛 मेरी समिति" },
  "dairy.hub.my_orders": { en: "📦 My orders", hi: "📦 मेरे ऑर्डर" },

  // goatery hub
  "dairy.goatery.title": { en: "Goatery", hi: "बकरी पालन" },
  "dairy.goatery.sub": { en: "Register your herd, log costs & sales, see your P&L", hi: "अपना झुंड दर्ज करें, खर्च व बिक्री लिखें, लाभ-हानि देखें" },
  "dairy.goatery.animals": { en: "My goats", hi: "मेरी बकरियाँ" },
  "dairy.goatery.animals_desc": { en: "Register & track your herd", hi: "अपना झुंड दर्ज करें और देखें" },
  "dairy.goatery.log_cost": { en: "Log a cost", hi: "खर्च दर्ज करें" },
  "dairy.goatery.log_cost_desc": { en: "Feed, medicine, breeding…", hi: "दाना, दवा, प्रजनन…" },
  "dairy.goatery.log_sale": { en: "Log a sale", hi: "बिक्री दर्ज करें" },
  "dairy.goatery.log_sale_desc": { en: "Animal / milk / manure", hi: "पशु / दूध / गोबर" },
  "dairy.goatery.pnl": { en: "Profit & loss", hi: "लाभ-हानि" },
  "dairy.goatery.pnl_desc": { en: "Revenue − cost, your credit file", hi: "आय − खर्च, आपकी क्रेडिट फ़ाइल" },
  "dairy.goatery.edit": { en: "Edit herd counts", hi: "झुंड की संख्या बदलें" },
  "dairy.goatery.edit_desc": { en: "Stall-fed, grazing, sheep", hi: "बंधी, चराई, भेड़" },

  // poultry hub
  "dairy.poultry.title": { en: "Poultry", hi: "मुर्गी पालन" },
  "dairy.poultry.sub": { en: "Register your flock, log costs & sales, see your P&L", hi: "अपना झुंड दर्ज करें, खर्च व बिक्री लिखें, लाभ-हानि देखें" },
  "dairy.poultry.animals": { en: "My flock", hi: "मेरा झुंड" },
  "dairy.poultry.animals_desc": { en: "Register & track your birds", hi: "अपने पक्षी दर्ज करें और देखें" },
  "dairy.poultry.log_cost": { en: "Log a cost", hi: "खर्च दर्ज करें" },
  "dairy.poultry.log_cost_desc": { en: "Feed, medicine, chicks…", hi: "दाना, दवा, चूज़े…" },
  "dairy.poultry.log_sale": { en: "Log a sale", hi: "बिक्री दर्ज करें" },
  "dairy.poultry.log_sale_desc": { en: "Birds / eggs", hi: "पक्षी / अंडे" },
  "dairy.poultry.pnl": { en: "Profit & loss", hi: "लाभ-हानि" },
  "dairy.poultry.pnl_desc": { en: "Revenue − cost, your credit file", hi: "आय − खर्च, आपकी क्रेडिट फ़ाइल" },
  "dairy.poultry.edit": { en: "Edit flock counts", hi: "झुंड की संख्या बदलें" },
  "dairy.poultry.edit_desc": { en: "Broilers / layers / native", hi: "ब्रॉयलर / अंडा / देसी" },
  "dairy.poultry.coming_soon": { en: "Detailed per-flock tracking (vaccinations, feed, sales) arrives in a future release.", hi: "प्रति-झुंड विस्तृत जानकारी (टीके, दाना, बिक्री) आगे किसी अपडेट में आएगी।" },

  // ── setup-dairy ──
  "dairy.setup.edit_title": { en: "Edit your herd", hi: "अपना झुंड बदलें" },
  "dairy.setup.new_title": { en: "Tell us about your herd", hi: "अपने झुंड के बारे में बताएँ" },
  "dairy.setup.edit_sub": { en: "Adjust the counts to match your current herd.", hi: "अपने मौजूदा झुंड के अनुसार संख्या बदलें।" },
  "dairy.setup.new_sub": { en: "Just enter how many animals you have. You can name them later.", hi: "बस बताएँ आपके पास कितने पशु हैं। नाम बाद में रख सकते हैं।" },
  "dairy.setup.total": { en: "Total animals", hi: "कुल पशु" },
  "dairy.setup.save_changes": { en: "Save changes", hi: "बदलाव सहेजें" },
  "dairy.setup.save_lock": { en: "Save & lock", hi: "सहेजें और लॉक करें" },
  "dairy.setup.hint": { en: "You can add, rename, or remove individual animals later from the Dairy card.", hi: "अलग-अलग पशु आप बाद में डेयरी कार्ड से जोड़, नाम बदल या हटा सकते हैं।" },
  "dairy.setup.need_one_title": { en: "Add at least one animal", hi: "कम से कम एक पशु जोड़ें" },
  "dairy.setup.need_one_msg": { en: "Tap + to add cows or buffaloes before saving.", hi: "सहेजने से पहले + दबाकर गाय या भैंस जोड़ें।" },
  "dairy.setup.saved_title": { en: "Data Saved", hi: "जानकारी सहेजी गई" },
  "dairy.setup.saved_msg": { en: "Dairy details saved successfully.", hi: "डेयरी की जानकारी सफलतापूर्वक सहेजी गई।" },
  "dairy.setup.continue_setup": { en: "Continue Setup", hi: "सेटअप जारी रखें" },
  "dairy.setup.back_home": { en: "Back to Home", hi: "होम पर जाएँ" },
  "dairy.setup.save_failed": { en: "Save failed", hi: "सहेजना विफल" },
  "dairy.setup.please_try_again": { en: "Please try again.", hi: "कृपया फिर कोशिश करें।" },

  // ── setup-goatery ──
  "dairy.gsetup.sub": { en: "Detailed goat + sheep tracking is coming soon. For now, enter the rough count.", hi: "बकरी और भेड़ की विस्तृत जानकारी जल्द आएगी। अभी अनुमानित संख्या दर्ज करें।" },
  "dairy.gsetup.total": { en: "Total animals", hi: "कुल पशु" },
  "dairy.gsetup.need_one_title": { en: "Add at least one animal", hi: "कम से कम एक पशु जोड़ें" },
  "dairy.gsetup.need_one_msg": { en: "Enter a herd count before saving.", hi: "सहेजने से पहले झुंड की संख्या दर्ज करें।" },
  "dairy.gsetup.no_sub_title": { en: "Subscription not found", hi: "सदस्यता नहीं मिली" },
  "dairy.gsetup.no_sub_msg": { en: "Add GOATERY as an activity first.", hi: "पहले बकरी पालन को गतिविधि के रूप में जोड़ें।" },
  "dairy.gsetup.saved_msg": { en: "Goatery details saved successfully.", hi: "बकरी पालन की जानकारी सफलतापूर्वक सहेजी गई।" },

  // ── setup-poultry ──
  "dairy.psetup.edit_title": { en: "Edit your flock", hi: "अपना झुंड बदलें" },
  "dairy.psetup.new_title": { en: "Tell us about your flock", hi: "अपने झुंड के बारे में बताएँ" },
  "dairy.psetup.sub": { en: "Detailed poultry tracking is coming soon. For now, enter the rough count per type.", hi: "मुर्गी की विस्तृत जानकारी जल्द आएगी। अभी हर प्रकार की अनुमानित संख्या दर्ज करें।" },
  "dairy.psetup.big_flock": { en: "Big flock? Type the count", hi: "बड़ा झुंड? संख्या टाइप करें" },
  "dairy.psetup.broilers_count": { en: "Broilers · count", hi: "ब्रॉयलर · संख्या" },
  "dairy.psetup.layers_count": { en: "Layers · count", hi: "अंडा मुर्गी · संख्या" },
  "dairy.psetup.total": { en: "Total birds", hi: "कुल पक्षी" },
  "dairy.psetup.need_one_title": { en: "Add at least one bird", hi: "कम से कम एक पक्षी जोड़ें" },
  "dairy.psetup.need_one_msg": { en: "Enter a flock count before saving.", hi: "सहेजने से पहले झुंड की संख्या दर्ज करें।" },
  "dairy.psetup.no_sub_title": { en: "Subscription not found", hi: "सदस्यता नहीं मिली" },
  "dairy.psetup.no_sub_msg": { en: "Add POULTRY as an activity first.", hi: "पहले मुर्गी पालन को गतिविधि के रूप में जोड़ें।" },
  "dairy.psetup.saved_msg": { en: "Poultry details saved successfully.", hi: "मुर्गी पालन की जानकारी सफलतापूर्वक सहेजी गई।" },

  // ── dairy-onboarding ──
  "dairy.onb.title": { en: "Dairy Setup", hi: "डेयरी सेटअप" },
  "dairy.onb.subtitle": { en: "Dairy profile", hi: "डेयरी प्रोफ़ाइल" },
  "dairy.onb.coop_count": { en: "Cooperative & count", hi: "सहकारी और संख्या" },
  "dairy.onb.saved_title": { en: "Saved", hi: "सहेजा गया" },
  "dairy.onb.saved_msg": { en: "Dairy profile saved successfully", hi: "डेयरी प्रोफ़ाइल सफलतापूर्वक सहेजी गई" },
  "dairy.onb.continue": { en: "Continue", hi: "जारी रखें" },
  "dairy.onb.save_failed": { en: "Failed to save profile", hi: "प्रोफ़ाइल सहेजना विफल" },
  "dairy.onb.network_error": { en: "Network error", hi: "नेटवर्क त्रुटि" },
  "dairy.onb.tier_small": { en: "Small\n1–4", hi: "छोटा\n1–4" },
  "dairy.onb.tier_medium": { en: "Medium\n5–10", hi: "मध्यम\n5–10" },
  "dairy.onb.tier_large": { en: "Large\n10+", hi: "बड़ा\n10+" },
  "dairy.onb.pay_cash": { en: "Cash", hi: "नकद" },
  "dairy.onb.pay_upi": { en: "UPI", hi: "यूपीआई" },
  "dairy.onb.pay_bank": { en: "Bank", hi: "बैंक" },
  "dairy.onb.pay_credit": { en: "Credit", hi: "उधार" },

  // ── dairy-animals ──
  "dairy.animals.title": { en: "My Herd", hi: "मेरे पशु" },
  "dairy.animals.add": { en: "+ Add Animal", hi: "+ पशु जोड़ें" },
  "dairy.animals.new": { en: "New Animal", hi: "नया पशु" },
  "dairy.animals.tag": { en: "Tag Number", hi: "टैग नंबर" },
  "dairy.animals.name": { en: "Name", hi: "नाम" },
  "dairy.animals.species": { en: "Species", hi: "प्रजाति" },
  "dairy.animals.breed": { en: "Breed Code", hi: "नस्ल कोड" },
  "dairy.animals.gender": { en: "Gender", hi: "लिंग" },
  "dairy.animals.dob": { en: "Date of Birth (YYYY-MM-DD)", hi: "जन्म तिथि (YYYY-MM-DD)" },
  "dairy.animals.lifecycle": { en: "Lifecycle Stage", hi: "जीवन-चरण" },
  "dairy.animals.purchase_cost": { en: "Purchase Cost (₹)", hi: "खरीद मूल्य (₹)" },
  "dairy.animals.purchase_date": { en: "Purchase Date", hi: "खरीद तिथि" },
  "dairy.animals.save": { en: "Save Animal", hi: "पशु सहेजें" },
  "dairy.animals.missing_title": { en: "Missing", hi: "अधूरा" },
  "dairy.animals.missing_msg": { en: "Enter at least a name or tag number", hi: "कम से कम एक नाम या टैग नंबर दर्ज करें" },
  "dairy.animals.added_title": { en: "Added", hi: "जोड़ा गया" },
  "dairy.animals.added_msg": { en: "Animal added to herd", hi: "पशु झुंड में जोड़ा गया" },
  "dairy.animals.add_failed": { en: "Failed to add animal", hi: "पशु जोड़ना विफल" },
  "dairy.animals.empty": { en: "No animals yet", hi: "अभी कोई पशु नहीं" },
  "dairy.animals.unnamed": { en: "Unnamed", hi: "बिना नाम" },
  "dairy.animals.bought": { en: "Bought", hi: "खरीदा" },
  // species labels
  "dairy.species.CATTLE": { en: "Cattle", hi: "गाय" },
  "dairy.species.BUFFALO": { en: "Buffalo", hi: "भैंस" },
  "dairy.species.GOAT": { en: "Goat", hi: "बकरी" },
  "dairy.species.SHEEP": { en: "Sheep", hi: "भेड़" },
  "dairy.species.PIG": { en: "Pig", hi: "सूअर" },
  "dairy.species.POULTRY": { en: "Poultry", hi: "मुर्गी" },
  // gender
  "dairy.gender.FEMALE": { en: "Female", hi: "मादा" },
  "dairy.gender.MALE": { en: "Male", hi: "नर" },
  // lifecycle stages
  "dairy.lc.CALF": { en: "Calf", hi: "बछड़ा" },
  "dairy.lc.HEIFER": { en: "Heifer", hi: "बछिया" },
  "dairy.lc.DRY": { en: "Dry", hi: "सूखी" },
  "dairy.lc.EARLY_LACTATION": { en: "Early Lact.", hi: "शुरुआती दूध" },
  "dairy.lc.PEAK_LACTATION": { en: "Peak Lact.", hi: "चरम दूध" },
  "dairy.lc.LATE_LACTATION": { en: "Late Lact.", hi: "अंतिम दूध" },
  "dairy.lc.PREGNANT": { en: "Pregnant", hi: "गाभिन" },
  "dairy.lc.BREEDING": { en: "Breeding", hi: "प्रजनन" },

  // ── dairy-logbook ──
  "dairy.log.setup_first_title": { en: "Set up your dairy first", hi: "पहले अपनी डेयरी सेट करें" },
  "dairy.log.start_setup": { en: "Start Setup", hi: "शुरू करें" },
  "dairy.log.title": { en: "Dairy Logbook", hi: "डेयरी बही" },
  "dairy.log.tier": { en: "tier", hi: "श्रेणी" },
  "dairy.log.entry_weekly": { en: "Weekly", hi: "साप्ताहिक" },
  "dairy.log.entry_daily": { en: "Daily", hi: "रोज़ाना" },
  "dairy.log.entry_word": { en: "entry", hi: "प्रविष्टि" },
  "dairy.log.last_14": { en: "Last 14 days", hi: "पिछले 14 दिन" },
  "dairy.log.revenue": { en: "Revenue", hi: "आय" },
  "dairy.log.cost": { en: "Cost", hi: "खर्च" },
  "dairy.log.net": { en: "Net", hi: "शुद्ध" },
  "dairy.log.view_full_pnl": { en: "View full P&L →", hi: "पूरी लाभ-हानि देखें →" },
  "dairy.log.my_herd": { en: "My Herd", hi: "मेरे पशु" },
  "dairy.log.animals_active": { en: "animals active", hi: "पशु सक्रिय" },
  "dairy.log.lactating": { en: "lactating", hi: "दूध देने वाले" },
  "dairy.log.pregnant": { en: "pregnant", hi: "गाभिन" },
  "dairy.log.quick_actions": { en: "Quick Actions", hi: "त्वरित क्रियाएँ" },
  "dairy.log.act_milk": { en: "Log Milk Sale", hi: "दूध बिक्री" },
  "dairy.log.act_expense": { en: "Log Expense", hi: "खर्च" },
  "dairy.log.act_animals": { en: "My Animals", hi: "मेरे पशु" },
  "dairy.log.act_vet": { en: "Vet Treatment", hi: "पशु चिकित्सा" },
  "dairy.log.act_breeding": { en: "Breeding", hi: "प्रजनन" },
  "dairy.log.act_pnl": { en: "P&L Report", hi: "लाभ-हानि" },

  // ── dairy-pnl ──
  "dairy.pnl.title": { en: "P&L", hi: "लाभ-हानि" },
  "dairy.pnl.herd_total": { en: "Herd Total", hi: "पूरा झुंड" },
  "dairy.pnl.per_animal": { en: "Per-Animal", hi: "प्रति पशु" },
  "dairy.pnl.net_profit": { en: "Net Profit", hi: "शुद्ध मुनाफ़ा" },
  "dairy.pnl.revenue": { en: "Revenue", hi: "आय" },
  "dairy.pnl.cost": { en: "Cost", hi: "खर्च" },
  "dairy.pnl.formal": { en: "Formal", hi: "औपचारिक" },
  "dairy.pnl.informal": { en: "Informal", hi: "अनौपचारिक" },
  "dairy.pnl.cost_breakdown": { en: "Cost Breakdown", hi: "खर्च विवरण" },
  "dairy.pnl.no_costs": { en: "No costs recorded in this period", hi: "इस अवधि में कोई खर्च दर्ज नहीं" },
  "dairy.pnl.no_animals": { en: "No animals in herd", hi: "झुंड में कोई पशु नहीं" },
  "dairy.pnl.unnamed": { en: "Unnamed", hi: "बिना नाम" },
  "dairy.pnl.direct": { en: "direct:", hi: "सीधा:" },
  "dairy.pnl.allocated": { en: "allocated:", hi: "आवंटित:" },
  "dairy.pnl.revenue_label": { en: "Revenue:", hi: "आय:" },
  "dairy.pnl.cost_label": { en: "Cost:", hi: "खर्च:" },
};
export default frag;
