/** i18n fragment: pashu screens. Keys are "namespace.key" → { en, hi }. */
const frag: Record<string, { en: string; hi: string }> = {
  // ── shared across pashu screens ──
  "pashu.si": { en: "SI", hi: "बीमित राशि" },
  "pashu.of": { en: "of", hi: "में से" },
  "pashu.covered_lc": { en: "covered", hi: "सुरक्षित" },
  "pashu.uninsured": { en: "Uninsured", hi: "असुरक्षित" },
  "pashu.insured": { en: "Insured", hi: "सुरक्षित" },
  "pashu.covered_badge": { en: "Covered", hi: "सुरक्षित" },
  "pashu.animal_word": { en: "Animal", hi: "पशु" },
  "pashu.untagged": { en: "Untagged", hi: "बिना टैग" },
  "pashu.cannot_connect": { en: "Cannot connect.", hi: "कनेक्ट नहीं हो पा रहा।" },

  // ── pashu-home ──
  "pashu.home.my_protection": { en: "My protection", hi: "मेरी सुरक्षा" },
  "pashu.home.covered_default": { en: "0 of 0 covered", hi: "0 में से 0 सुरक्षित" },
  "pashu.home.si_active": { en: "Sum insured active", hi: "सक्रिय बीमित राशि" },
  "pashu.home.uncovered": { en: "uncovered", hi: "असुरक्षित" },
  "pashu.home.policies": { en: "Policies", hi: "पॉलिसी" },
  "pashu.home.no_policies": { en: "No policies yet. Insure your first animal to protect your herd.", hi: "अभी कोई पॉलिसी नहीं। अपने झुंड की रक्षा के लिए पहले पशु का बीमा करें।" },
  "pashu.home.policy": { en: "Policy", hi: "पॉलिसी" },
  "pashu.home.you_pay": { en: "You pay", hi: "आप देते हैं" },
  "pashu.home.ends": { en: "ends", hi: "समाप्ति" },
  "pashu.home.footer_muzzle": { en: "Muzzle biometrics are a second factor — your 12-digit NDDB tag stays the statutory identity.", hi: "मुँह की बायोमेट्रिक दूसरा माध्यम है — आपका 12-अंकों का NDDB टैग ही वैधानिक पहचान है।" },

  // ── actions (home) ──
  "pashu.act.animals": { en: "My animals", hi: "मेरे पशु" },
  "pashu.act.quote": { en: "Get a quote", hi: "अनुमान लें" },
  "pashu.act.enrol": { en: "Insure an animal", hi: "पशु का बीमा करें" },
  "pashu.act.claim": { en: "Report a death", hi: "मृत्यु सूचना दें" },
  "pashu.act.renew": { en: "Renewals", hi: "नवीनीकरण" },

  // ── pashu-animals ──
  "pashu.animals.my_herd": { en: "My herd", hi: "मेरा झुंड" },
  "pashu.animals.uninsured_suffix": { en: "animals still uninsured", hi: "पशु अभी भी असुरक्षित हैं" },
  "pashu.animals.empty": { en: "No animals in your register yet. Add animals in your dairy register — your protection is built from there.", hi: "अभी आपके रजिस्टर में कोई पशु नहीं। अपने डेयरी रजिस्टर में पशु जोड़ें — आपकी सुरक्षा वहीं से बनती है।" },
  "pashu.animals.go_to_animals": { en: "Go to my animals", hi: "मेरे पशुओं पर जाएँ" },
  "pashu.animals.insure_cta": { en: "Insure ›", hi: "बीमा करें ›" },
  "pashu.animals.footer_tag": { en: "The 12-digit NDDB ear tag is the statutory identity. Muzzle biometrics are only a second factor.", hi: "12-अंकों का NDDB कान का टैग ही वैधानिक पहचान है। मुँह की बायोमेट्रिक केवल दूसरा माध्यम है।" },

  // ── pashu-vault ──
  "pashu.vault.not_found": { en: "Policy not found.", hi: "पॉलिसी नहीं मिली।" },
  "pashu.vault.doc_title": { en: "Policy document", hi: "पॉलिसी दस्तावेज़" },
  "pashu.vault.doc_opening": { en: "Opening from your vault (DigiLocker). This copy is delivered to you — never held by the vet.", hi: "आपकी तिजोरी (डिजिलॉकर) से खोल रहे हैं। यह प्रति आपको दी जाती है — पशु-चिकित्सक के पास नहीं रहती।" },
  "pashu.vault.not_ready": { en: "Not ready", hi: "अभी तैयार नहीं" },
  "pashu.vault.doc_pending": { en: "The policy document will appear here once the insurer issues it.", hi: "बीमा कंपनी द्वारा जारी होते ही पॉलिसी दस्तावेज़ यहाँ दिखेगा।" },
  "pashu.vault.sum_insured": { en: "Sum insured", hi: "बीमित राशि" },
  "pashu.vault.you_pay": { en: "You pay", hi: "आप देते हैं" },
  "pashu.vault.total_premium": { en: "Total premium", hi: "कुल प्रीमियम" },
  "pashu.vault.cover": { en: "Cover", hi: "बीमा अवधि" },
  "pashu.vault.policy_no": { en: "Policy no.", hi: "पॉलिसी नं." },
  "pashu.vault.insurer": { en: "Insurer", hi: "बीमा कंपनी" },
  "pashu.vault.waiting_pre": { en: "⏳ 21-day waiting period until", hi: "⏳ प्रतीक्षा अवधि (21 दिन) —" },
  "pashu.vault.waiting_post": { en: "Death claims before this date are not payable (NLM).", hi: "इस तारीख से पहले मृत्यु दावे देय नहीं हैं (NLM)।" },
  "pashu.vault.insured_animals": { en: "Insured animals", hi: "बीमित पशु" },
  "pashu.vault.no_animals_linked": { en: "No animals linked.", hi: "कोई पशु जुड़ा नहीं।" },
  "pashu.vault.valued": { en: "Valued", hi: "मूल्यांकन" },
  "pashu.vault.photo_owner": { en: "📷 owner", hi: "📷 मालिक" },
  "pashu.vault.photo_tag": { en: "📷 tag", hi: "📷 टैग" },
  "pashu.vault.premium_trail": { en: "Premium trail", hi: "प्रीमियम विवरण" },
  "pashu.vault.no_entries": { en: "No entries yet.", hi: "अभी कोई प्रविष्टि नहीं।" },
  "pashu.vault.view_doc": { en: "📄 View policy document", hi: "📄 पॉलिसी दस्तावेज़ देखें" },
  "pashu.vault.file_claim": { en: "📋 File a claim on this cover", hi: "📋 इस बीमा पर दावा करें" },
  "pashu.vault.renew": { en: "🔄 Renew", hi: "🔄 नवीनीकरण" },
  "pashu.vault.footer": { en: "Your policy is delivered to you, not the vet. Keep it in your vault.", hi: "आपकी पॉलिसी आपको दी जाती है, पशु-चिकित्सक को नहीं। इसे अपनी तिजोरी में रखें।" },
  // premium ledger entry labels
  "pashu.vault.pl.farmer_debit": { en: "Your share (via KCC)", hi: "आपका हिस्सा (केसीसी से)" },
  "pashu.vault.pl.subsidy_central": { en: "Central subsidy", hi: "केंद्रीय सब्सिडी" },
  "pashu.vault.pl.subsidy_state": { en: "State subsidy", hi: "राज्य सब्सिडी" },
  "pashu.vault.pl.financed_kcc": { en: "Financed on KCC", hi: "केसीसी पर वित्तपोषित" },
  "pashu.vault.pl.refund": { en: "Refund", hi: "वापसी" },

  // ── pashu-quote ──
  "pashu.quote.choose_plan": { en: "Choose a plan", hi: "योजना चुनें" },
  "pashu.quote.market_value": { en: "Market value (₹)", hi: "बाज़ार मूल्य (₹)" },
  "pashu.quote.region_note": { en: "Himalayan (Uttarakhand) · centre:state 90:10 · 21-day waiting", hi: "हिमालयी (उत्तराखंड) · केंद्र:राज्य 90:10 · 21-दिन प्रतीक्षा" },
  "pashu.quote.premium_pre": { en: "Premium", hi: "प्रीमियम" },
  "pashu.quote.month_term": { en: "month · ceiling", hi: "माह · अधिकतम" },
  "pashu.quote.sum_insured": { en: "Sum insured", hi: "बीमित राशि" },
  "pashu.quote.total_premium": { en: "Total premium", hi: "कुल प्रीमियम" },
  "pashu.quote.you_pay_15": { en: "You pay (15%)", hi: "आप देते हैं (15%)" },
  "pashu.quote.govt_85": { en: "Govt subsidy (85%)", hi: "सरकारी सब्सिडी (85%)" },
  "pashu.quote.cu_cap": { en: "Cattle-unit cap", hi: "पशु-इकाई सीमा" },
  "pashu.quote.cu_using": { en: "using", hi: "उपयोग" },
  "pashu.quote.insure_this": { en: "Insure this animal", hi: "इस पशु का बीमा करें" },

  // ── pashu-enrol ──
  "pashu.enrol.step.draft": { en: "Draft", hi: "मसौदा" },
  "pashu.enrol.step.tag": { en: "Tag + photos", hi: "टैग + फ़ोटो" },
  "pashu.enrol.step.vet": { en: "Vet exam", hi: "पशु-चिकित्सक जाँच" },
  "pashu.enrol.step.valued": { en: "Valued", hi: "मूल्यांकन" },
  "pashu.enrol.step.premium": { en: "Premium (KCC)", hi: "प्रीमियम (केसीसी)" },
  "pashu.enrol.step.issued": { en: "Policy issued", hi: "पॉलिसी जारी" },
  "pashu.enrol.consent_needed": { en: "Consent needed", hi: "सहमति आवश्यक" },
  "pashu.enrol.consent_msg": { en: "Please consent to premium debit via KCC (DPDP).", hi: "कृपया केसीसी से प्रीमियम कटौती की सहमति दें (DPDP)।" },
  "pashu.enrol.tag_title": { en: "Tag", hi: "टैग" },
  "pashu.enrol.tag_msg": { en: "Enter the 12-digit NDDB ear tag.", hi: "12-अंकों का NDDB कान का टैग दर्ज करें।" },
  "pashu.enrol.could_not_start": { en: "Could not start enrolment", hi: "नामांकन शुरू नहीं हो सका" },
  "pashu.enrol.submitted": { en: "Submitted", hi: "जमा हो गया" },
  "pashu.enrol.submitted_msg": { en: "A VCI vet will examine your animal next.", hi: "अब एक VCI पशु-चिकित्सक आपके पशु की जाँच करेगा।" },
  "pashu.enrol.tag_failed": { en: "Tag failed", hi: "टैग विफल" },
  "pashu.enrol.conn_check": { en: "Cannot connect. Check your connection.", hi: "कनेक्ट नहीं हो पा रहा। अपना कनेक्शन जाँचें।" },
  "pashu.enrol.title": { en: "Enrolment", hi: "नामांकन" },
  "pashu.enrol.which_animal": { en: "Which animal?", hi: "कौन-सा पशु?" },
  "pashu.enrol.all_covered": { en: "All your animals are covered, or none registered.", hi: "आपके सभी पशु सुरक्षित हैं, या कोई पंजीकृत नहीं है।" },
  "pashu.enrol.statutory_identity": { en: "Statutory identity (required)", hi: "वैधानिक पहचान (आवश्यक)" },
  "pashu.enrol.tag_placeholder": { en: "12-digit NDDB ear tag", hi: "12-अंकों का NDDB कान का टैग" },
  "pashu.enrol.photo_owner": { en: "📷 Owner + animal", hi: "📷 मालिक + पशु" },
  "pashu.enrol.photo_tag": { en: "📷 Tag close-up", hi: "📷 टैग नज़दीक से" },
  "pashu.enrol.muzzle_check": { en: "Also capture a muzzle burst (2nd factor, runs on-device; the gallery never leaves the platform)", hi: "मुँह की तस्वीरें भी लें (दूसरा माध्यम, डिवाइस पर चलता है; गैलरी प्लेटफ़ॉर्म से बाहर नहीं जाती)" },
  "pashu.enrol.muzzle_note": { en: "Optional. Muzzle biometrics never replace the tag and never gate your policy.", hi: "वैकल्पिक। मुँह की बायोमेट्रिक कभी टैग की जगह नहीं लेती और आपकी पॉलिसी नहीं रोकती।" },
  "pashu.enrol.premium_consent": { en: "I consent to premium debit via my KCC account (DPDP, ¶32–33)", hi: "मैं अपने केसीसी खाते से प्रीमियम कटौती की सहमति देता/देती हूँ (DPDP, ¶32–33)" },
  "pashu.enrol.submit": { en: "Submit for vet examination", hi: "पशु-चिकित्सक जाँच के लिए भेजें" },

  // ── pashu-claim ──
  "pashu.claim.doc.death": { en: "Death intimation", hi: "मृत्यु सूचना" },
  "pashu.claim.doc.pm": { en: "Post-mortem (VCI vet)", hi: "पोस्टमार्टम (VCI पशु-चिकित्सक)" },
  "pashu.claim.doc.tag_photo": { en: "Ear-tag photo", hi: "कान के टैग की फ़ोटो" },
  "pashu.claim.doc.form": { en: "Signed claim form", hi: "हस्ताक्षरित दावा फ़ॉर्म" },
  "pashu.claim.pick_policy": { en: "Pick a policy", hi: "एक पॉलिसी चुनें" },
  "pashu.claim.which_died": { en: "Which insured animal died?", hi: "कौन-से बीमित पशु की मृत्यु हुई?" },
  "pashu.claim.could_not_file": { en: "Could not file", hi: "दावा दर्ज नहीं हो सका" },
  "pashu.claim.could_not_attach": { en: "Could not attach", hi: "संलग्न नहीं हो सका" },
  "pashu.claim.submitted": { en: "Submitted", hi: "जमा हो गया" },
  "pashu.claim.submitted_msg": { en: "Your claim is under review on a 15-day clock.", hi: "आपका दावा 15-दिन की समय-सीमा पर समीक्षा में है।" },
  "pashu.claim.not_submitted": { en: "Not submitted", hi: "जमा नहीं हुआ" },
  "pashu.claim.complete_four": { en: "Complete all four documents first.", hi: "पहले चारों दस्तावेज़ पूरे करें।" },
  "pashu.claim.banner": { en: "NLM asks for exactly four documents — never more.", hi: "NLM केवल चार दस्तावेज़ माँगता है — इससे अधिक कभी नहीं।" },
  "pashu.claim.status": { en: "Claim status", hi: "दावा स्थिति" },
  "pashu.claim.checklist": { en: "4-document checklist", hi: "4-दस्तावेज़ सूची" },
  "pashu.claim.attach": { en: "Attach", hi: "संलग्न करें" },
  "pashu.claim.settlement_clock": { en: "Settlement clock", hi: "निपटान समय" },
  "pashu.claim.settlement_note": { en: "15 days from documents complete. On breach, 12% p.a. compound penal interest accrues in your favour. Every step is on a tamper-evident hash chain 🔒.", hi: "दस्तावेज़ पूरे होने से 15 दिन। देरी पर आपके पक्ष में 12% वार्षिक चक्रवृद्धि दंड ब्याज जुड़ता है। हर चरण छेड़छाड़-रोधी हैश-श्रृंखला पर है 🔒।" },
  "pashu.claim.penal_interest": { en: "Penal interest", hi: "दंड ब्याज" },
  "pashu.claim.submit_docs": { en: "Submit documents", hi: "दस्तावेज़ जमा करें" },
  "pashu.claim.back_to_claims": { en: "Back to claims", hi: "दावों पर वापस" },
  "pashu.claim.report_death": { en: "Report a death", hi: "मृत्यु सूचना दें" },
  "pashu.claim.no_active_policy": { en: "No active policy to claim on.", hi: "दावे के लिए कोई सक्रिय पॉलिसी नहीं।" },
  "pashu.claim.cause_placeholder": { en: "Cause (disease / accident…)", hi: "कारण (बीमारी / दुर्घटना…)" },
  "pashu.claim.file_claim": { en: "File claim", hi: "दावा दर्ज करें" },
  "pashu.claim.my_claims": { en: "My claims", hi: "मेरे दावे" },
  "pashu.claim.no_claims": { en: "No claims filed.", hi: "कोई दावा दर्ज नहीं।" },

  // ── pashu-renew ──
  "pashu.renew.renewed": { en: "Renewed", hi: "नवीनीकृत" },
  "pashu.renew.renewed_msg": { en: "Your cover continues — new term issued, no re-documentation.", hi: "आपका बीमा जारी है — नई अवधि जारी, कोई नए दस्तावेज़ नहीं।" },
  "pashu.renew.could_not_renew": { en: "Could not renew", hi: "नवीनीकरण नहीं हो सका" },
  "pashu.renew.auto_on_title": { en: "Auto-renew on", hi: "स्वतः नवीनीकरण चालू" },
  "pashu.renew.auto_on_msg": { en: "We'll renew this cover automatically on the due date.", hi: "हम इस बीमा को नियत तारीख पर अपने आप नवीनीकृत कर देंगे।" },
  "pashu.renew.could_not_optin": { en: "Could not opt in", hi: "चयन नहीं हो सका" },
  "pashu.renew.none_due": { en: "No renewals due. You're all covered.", hi: "कोई नवीनीकरण बाकी नहीं। आप पूरी तरह सुरक्षित हैं।" },
  "pashu.renew.due_title": { en: "Renewal due", hi: "नवीनीकरण बाकी" },
  "pashu.renew.due_word": { en: "Due", hi: "नियत" },
  "pashu.renew.note": { en: "One-tap renew clones your policy + tag + photos — zero re-documentation.", hi: "एक-टैप नवीनीकरण आपकी पॉलिसी + टैग + फ़ोटो की नकल करता है — कोई नए दस्तावेज़ नहीं।" },
  "pashu.renew.renew_now": { en: "Renew now", hi: "अभी नवीनीकरण करें" },
  "pashu.renew.auto_optin": { en: "Auto-renew next time (opt-in)", hi: "अगली बार स्वतः नवीनीकरण (चुनें)" },
  "pashu.renew.auto_is_on": { en: "✓ Auto-renew is on", hi: "✓ स्वतः नवीनीकरण चालू है" },
};
export default frag;
