/** i18n fragment: CIA (cattle induction) farmer screens. Keys are "namespace.key" → { en, hi }. */
const frag: Record<string, { en: string; hi: string }> = {
  // ── nav (header titles) ──
  "nav.cia_schemes": { en: "Cattle schemes", hi: "पशु योजनाएँ" },
  "nav.cia_scheme": { en: "Scheme details", hi: "योजना विवरण" },
  "nav.cia_eligibility": { en: "Am I eligible?", hi: "क्या मैं पात्र हूँ?" },
  "nav.cia_eoi": { en: "Express interest", hi: "रुचि दर्ज करें" },

  // ── home card ──
  "home.cia_title": { en: "Cattle induction scheme", hi: "पशु प्रेरण योजना" },
  "home.cia_sub": { en: "Subsidy + loan for a milch animal — recovered from milk", hi: "दुधारू पशु के लिए सब्सिडी + ऋण — दूध से वसूली" },

  // ── schemes list ──
  "cia.schemes.open_count": { en: "schemes open at your society", hi: "योजनाएँ आपकी समिति में खुली हैं" },
  "cia.schemes.subsidy": { en: "subsidy", hi: "सब्सिडी" },
  "cia.schemes.you_qualify": { en: "You likely qualify", hi: "आप संभवतः पात्र हैं" },
  "cia.schemes.check_criteria": { en: "Check the criteria", hi: "मापदंड देखें" },
  "cia.schemes.view": { en: "View", hi: "देखें" },
  "cia.schemes.none": { en: "No cattle schemes are open right now.", hi: "अभी कोई पशु योजना खुली नहीं है।" },
  "cia.schemes.ceiling": { en: "Ceiling", hi: "अधिकतम" },
  "cia.schemes.max": { en: "Max", hi: "अधिकतम" },
  "cia.schemes.min": { en: "Min", hi: "न्यूनतम" },

  // ── scheme detail ──
  "cia.scheme.what_you_get": { en: "What you get", hi: "आपको क्या मिलेगा" },
  "cia.scheme.subsidy_on_animal": { en: "Subsidy on the animal", hi: "पशु पर सब्सिडी" },
  "cia.scheme.your_contribution": { en: "Your contribution", hi: "आपका अंशदान" },
  "cia.scheme.price_ceiling": { en: "Price ceiling / animal", hi: "मूल्य सीमा / पशु" },
  "cia.scheme.per_member": { en: "Animals per member", hi: "प्रति सदस्य पशु" },
  "cia.scheme.who_can_apply": { en: "Who can apply", hi: "कौन आवेदन कर सकता है" },
  "cia.scheme.min_membership": { en: "Min DCS membership", hi: "न्यूनतम समिति सदस्यता" },
  "cia.scheme.min_milk": { en: "Avg monthly milk value", hi: "औसत मासिक दूध मूल्य" },
  "cia.scheme.what_needed": { en: "What you'll need", hi: "आपको क्या चाहिए" },
  "cia.scheme.check_eligibility": { en: "Check my eligibility", hi: "मेरी पात्रता जाँचें" },
  "cia.scheme.interested": { en: "Interested", hi: "रुचि है" },
  "cia.scheme.months": { en: "mo", hi: "माह" },
  "cia.scheme.up_to": { en: "up to", hi: "तक" },

  // ── eligibility ──
  "cia.elig.checking_for": { en: "Checking for", hi: "जाँच रहे हैं" },
  "cia.elig.change": { en: "Change", hi: "बदलें" },
  "cia.elig.likely": { en: "Likely eligible", hi: "संभवतः पात्र" },
  "cia.elig.likely_sub": { en: "You appear to meet this scheme's basic criteria.", hi: "आप इस योजना के बुनियादी मापदंड पूरे करते दिखते हैं।" },
  "cia.elig.not_yet": { en: "Not yet — here's why", hi: "अभी नहीं — कारण नीचे" },
  "cia.elig.guide": { en: "A GUIDE, NOT AN APPROVAL", hi: "मार्गदर्शन, स्वीकृति नहीं" },
  "cia.elig.link_membership": { en: "Link your dairy-society membership to check eligibility.", hi: "पात्रता जाँचने के लिए अपनी समिति सदस्यता जोड़ें।" },
  "cia.elig.express": { en: "Express interest", hi: "रुचि दर्ज करें" },

  // ── EOI ──
  "cia.eoi.join": { en: "Join", hi: "जुड़ें" },
  "cia.eoi.tell_society": { en: "Tell your dairy society you're interested. No cost, no commitment — the board will review and get back to you.", hi: "अपनी समिति को बताएँ कि आप इच्छुक हैं। कोई शुल्क नहीं, कोई बाध्यता नहीं — बोर्ड समीक्षा कर आपको बताएगा।" },
  "cia.eoi.scheme": { en: "Scheme", hi: "योजना" },
  "cia.eoi.society": { en: "Your society (DCS)", hi: "आपकी समिति" },
  "cia.eoi.shared_with": { en: "Shared with", hi: "किसे भेजा" },
  "cia.eoi.secretary": { en: "DCS secretary", hi: "समिति सचिव" },
  "cia.eoi.you_author": { en: "You author this step. Selection is the DCS board's decision.", hi: "यह कदम आप करते हैं। चयन समिति बोर्ड का निर्णय है।" },
  "cia.eoi.submit": { en: "Express interest", hi: "रुचि दर्ज करें" },
  "cia.eoi.shared_ok": { en: "Interest shared", hi: "रुचि भेज दी गई" },
  "cia.eoi.board_review": { en: "Your society has your request. The board will review it at the next selection meeting — you'll be notified either way.", hi: "आपकी समिति को अनुरोध मिल गया। बोर्ड अगली चयन बैठक में समीक्षा करेगा — आपको सूचित किया जाएगा।" },
  "cia.eoi.status_submitted": { en: "Interest submitted", hi: "रुचि दर्ज" },
  "cia.eoi.track": { en: "Track my status", hi: "मेरी स्थिति देखें" },
  "cia.eoi.done": { en: "Done", hi: "हो गया" },

  // ── application form + documents ──
  "nav.cia_application": { en: "Application", hi: "आवेदन" },
  "cia.app.complete_prompt": { en: "You're selected — complete your application", hi: "आप चयनित हैं — अपना आवेदन पूरा करें" },
  "cia.app.track_prompt": { en: "Track your application", hi: "अपना आवेदन देखें" },
  "cia.app.not_selected": { en: "You must be selected by your DCS board before you can apply. You'll be notified when that happens.", hi: "आवेदन से पहले आपकी समिति बोर्ड द्वारा चयन आवश्यक है। चयन होने पर आपको सूचित किया जाएगा।" },
  "cia.app.applicant": { en: "Applicant (from Aanchal ERP)", hi: "आवेदक (आँचल ईआरपी से)" },
  "cia.app.mobile": { en: "Mobile", hi: "मोबाइल" },
  "cia.app.society": { en: "Society / DCS", hi: "समिति / डीसीएस" },
  "cia.app.bank": { en: "Bank account (loan a/c)", hi: "बैंक खाता (ऋण खाता)" },
  "cia.app.how_many": { en: "How many cattle?", hi: "कितने पशु?" },
  "cia.app.breed": { en: "Preferred breed (optional)", hi: "पसंदीदा नस्ल (वैकल्पिक)" },
  "cia.app.breed_ph": { en: "e.g. HF crossbred", hi: "जैसे HF क्रॉसब्रेड" },
  "cia.app.documents": { en: "Documents (camera only)", hi: "दस्तावेज़ (केवल कैमरा)" },
  "cia.app.capture": { en: "Capture", hi: "फोटो लें" },
  "cia.app.retake": { en: "Retake", hi: "फिर से" },
  "cia.app.required": { en: "REQUIRED", hi: "आवश्यक" },
  "cia.app.optional": { en: "optional", hi: "वैकल्पिक" },
  "cia.app.captured": { en: "captured", hi: "लिया गया" },
  "cia.app.save_draft": { en: "Save draft", hi: "ड्राफ्ट सहेजें" },
  "cia.app.saved": { en: "Draft saved on this phone.", hi: "ड्राफ्ट इस फ़ोन पर सहेजा गया।" },
  "cia.app.submit": { en: "Submit", hi: "जमा करें" },
  "cia.app.n_of_m": { en: "mandatory documents captured", hi: "आवश्यक दस्तावेज़ लिए गए" },
  "cia.app.of": { en: "of", hi: "में से" },
  "cia.app.capture_first": { en: "Capture the mandatory documents before submitting.", hi: "जमा करने से पहले आवश्यक दस्तावेज़ लें।" },
  "cia.app.camera_denied": { en: "Camera permission is needed to capture documents.", hi: "दस्तावेज़ लेने के लिए कैमरा अनुमति चाहिए।" },
  "cia.app.submitted": { en: "Application submitted", hi: "आवेदन जमा हो गया" },
  "cia.app.submitted_sub": { en: "A route supervisor will visit to verify your details. You'll be notified of the next step.", hi: "मार्ग पर्यवेक्षक आपके विवरण सत्यापित करने आएँगे। अगले चरण की सूचना दी जाएगी।" },
  "cia.app.erp": { en: "ERP", hi: "ईआरपी" },

  // ── status tracker ──
  "nav.cia_status": { en: "My application", hi: "मेरा आवेदन" },
  "cia.st.current": { en: "Current step", hi: "वर्तमान चरण" },
  "cia.st.next": { en: "Next", hi: "आगे" },
  "cia.st.as_of": { en: "Status as of", hi: "स्थिति (तक)" },
  "cia.st.pending": { en: "pending", hi: "बाकी" },
  "cia.st.none": { en: "You haven't applied to a scheme yet.", hi: "आपने अभी किसी योजना में आवेदन नहीं किया।" },
  "cia.st.browse": { en: "Browse schemes", hi: "योजनाएँ देखें" },
  "cia.st.complete": { en: "Complete application", hi: "आवेदन पूरा करें" },
  "cia.st.fix": { en: "Fix & resubmit", hi: "ठीक कर पुनः जमा करें" },
  "cia.st.returned": { en: "Returned for correction", hi: "सुधार हेतु वापस" },
  "cia.st.not_selected": { en: "Not selected this cycle — you may re-apply.", hi: "इस चक्र में चयन नहीं — आप पुनः आवेदन कर सकते हैं।" },
  "cia.st.rejected": { en: "Your application was not sanctioned.", hi: "आपका आवेदन स्वीकृत नहीं हुआ।" },
  "cia.st.financials": { en: "Sanction & disbursement", hi: "स्वीकृति व वितरण" },
  "cia.st.subsidy": { en: "Subsidy transferred", hi: "सब्सिडी अंतरित" },
  "cia.st.loan": { en: "Loan disbursed", hi: "ऋण वितरित" },
  "cia.st.loan_ac": { en: "Loan a/c", hi: "ऋण खाता" },
  // step labels
  "cia.step.interest": { en: "Interest submitted", hi: "रुचि दर्ज" },
  "cia.step.dcs_review": { en: "Society reviewing", hi: "समिति समीक्षा" },
  "cia.step.selected": { en: "Selected by DCS board", hi: "बोर्ड द्वारा चयनित" },
  "cia.step.application": { en: "Application + documents", hi: "आवेदन व दस्तावेज़" },
  "cia.step.verify": { en: "Field verification", hi: "क्षेत्र सत्यापन" },
  "cia.step.duss": { en: "District scrutiny (DUSS)", hi: "जिला जाँच (डीयूएसएस)" },
  "cia.step.bank": { en: "Bank appraisal", hi: "बैंक मूल्यांकन" },
  "cia.step.sanctioned": { en: "Loan sanctioned", hi: "ऋण स्वीकृत" },
  "cia.step.disbursed": { en: "Subsidy + loan released", hi: "सब्सिडी व ऋण जारी" },
  "cia.step.purchase": { en: "Cattle purchase", hi: "पशु खरीद" },
  "cia.step.emi": { en: "Milk-linked repayment", hi: "दूध से वसूली" },
  "cia.step.closed": { en: "Loan closed", hi: "ऋण बंद" },
  // actors
  "cia.who.you": { en: "You", hi: "आप" },
  "cia.who.dcs": { en: "DCS secretary", hi: "समिति सचिव" },
  "cia.who.board": { en: "DCS board", hi: "समिति बोर्ड" },
  "cia.who.supervisor": { en: "Route supervisor", hi: "मार्ग पर्यवेक्षक" },
  "cia.who.duss": { en: "DUSS", hi: "डीयूएसएस" },
  "cia.who.bank": { en: "Cooperative bank", hi: "सहकारी बैंक" },

  // ── guided cattle purchase ──
  "nav.cia_purchase": { en: "Buy your animal", hi: "अपना पशु खरीदें" },
  "cia.pur.buy_hero": { en: "Buy your animal", hi: "अपना पशु खरीदें" },
  "cia.pur.disbursed": { en: "disbursed", hi: "वितरित" },
  "cia.pur.buy_one": { en: "Document your milch-animal purchase step by step.", hi: "अपने दुधारू पशु की खरीद चरण-दर-चरण दर्ज करें।" },
  "cia.pur.gate_lock": { en: "Seller payment stays locked until a vet certificate, transit & cattle insurance and your acknowledgment all exist — with a complete traceability chain.", hi: "पशु चिकित्सक प्रमाण, ट्रांज़िट व पशु बीमा और आपकी पुष्टि होने तक विक्रेता भुगतान बंद रहता है — पूरी ट्रेसबिलिटी शृंखला के साथ।" },
  "cia.pur.not_ready": { en: "This step opens after your loan is disbursed.", hi: "यह चरण आपके ऋण वितरण के बाद खुलेगा।" },
  // capture steps
  "cia.pur.s_seller": { en: "Seller details", hi: "विक्रेता विवरण" },
  "cia.pur.s_seller_sub": { en: "id + bank + relationship", hi: "पहचान + बैंक + संबंध" },
  "cia.pur.s_inspect": { en: "Cattle inspection", hi: "पशु निरीक्षण" },
  "cia.pur.s_inspect_sub": { en: "live photos + details", hi: "लाइव फोटो + विवरण" },
  "cia.pur.s_geo": { en: "Purchase location", hi: "खरीद स्थान" },
  "cia.pur.s_geo_sub": { en: "live GPS", hi: "लाइव जीपीएस" },
  "cia.pur.s_eartag": { en: "Ear tag", hi: "कान टैग" },
  "cia.pur.s_eartag_sub": { en: "12-digit + photo", hi: "12-अंक + फोटो" },
  "cia.pur.s_transport": { en: "Transport", hi: "परिवहन" },
  "cia.pur.s_transport_sub": { en: "vehicle + bill (optional)", hi: "वाहन + बिल (वैकल्पिक)" },
  "cia.pur.open": { en: "open", hi: "खोलें" },
  "cia.pur.edit": { en: "edit", hi: "बदलें" },
  "cia.pur.captured": { en: "captured", hi: "दर्ज" },
  "cia.pur.submit_capture": { en: "Submit purchase", hi: "खरीद जमा करें" },
  "cia.pur.submit_hint": { en: "Complete the required steps to submit.", hi: "जमा करने के लिए आवश्यक चरण पूरे करें।" },
  "cia.pur.submitted": { en: "Purchase recorded", hi: "खरीद दर्ज हुई" },
  // seller panel
  "cia.pur.seller_name": { en: "Seller name", hi: "विक्रेता का नाम" },
  "cia.pur.seller_id": { en: "ID proof photo", hi: "पहचान प्रमाण फोटो" },
  "cia.pur.seller_bank": { en: "Seller bank account", hi: "विक्रेता बैंक खाता" },
  "cia.pur.seller_bank_ph": { en: "account number / IFSC", hi: "खाता संख्या / IFSC" },
  "cia.pur.seller_photo": { en: "Seller photo", hi: "विक्रेता फोटो" },
  "cia.pur.seller_rel": { en: "Relationship to you", hi: "आपसे संबंध" },
  "cia.pur.seller_rel_ph": { en: "e.g. unrelated / known trader", hi: "जैसे असंबंधित / परिचित व्यापारी" },
  // inspection panel
  "cia.pur.animal_photos": { en: "Animal photos (live camera)", hi: "पशु फोटो (लाइव कैमरा)" },
  "cia.pur.add_photo": { en: "Add photo", hi: "फोटो जोड़ें" },
  "cia.pur.photos_count": { en: "photos", hi: "फोटो" },
  "cia.pur.species": { en: "Species", hi: "प्रजाति" },
  "cia.pur.cow": { en: "Cow", hi: "गाय" },
  "cia.pur.buffalo": { en: "Buffalo", hi: "भैंस" },
  "cia.pur.breed": { en: "Breed", hi: "नस्ल" },
  "cia.pur.sex": { en: "Sex", hi: "लिंग" },
  "cia.pur.female": { en: "Female", hi: "मादा" },
  "cia.pur.male": { en: "Male", hi: "नर" },
  // geo panel
  "cia.pur.capture_location": { en: "Capture location", hi: "स्थान दर्ज करें" },
  "cia.pur.locating": { en: "Getting your GPS position…", hi: "आपकी जीपीएस स्थिति ली जा रही है…" },
  "cia.pur.location_ok": { en: "Position captured", hi: "स्थान दर्ज" },
  "cia.pur.accuracy": { en: "accuracy", hi: "सटीकता" },
  "cia.pur.geofence_note": { en: "The geo-fence check runs on the server.", hi: "जियो-फेंस जाँच सर्वर पर होती है।" },
  "cia.pur.location_denied": { en: "Location permission is needed to capture the purchase place.", hi: "खरीद स्थान दर्ज करने के लिए स्थान अनुमति चाहिए।" },
  // ear-tag panel
  "cia.pur.eartag_label": { en: "12-digit NDDB ear tag", hi: "12-अंकीय NDDB कान टैग" },
  "cia.pur.eartag_photo": { en: "Ear-tag photo (live)", hi: "कान टैग फोटो (लाइव)" },
  "cia.pur.tag_valid": { en: "Valid — uniqueness checked on submit", hi: "मान्य — जमा पर विशिष्टता जाँची जाएगी" },
  "cia.pur.tag_need": { en: "digits", hi: "अंक" },
  "cia.pur.tag_dup": { en: "This ear tag is already used for another animal.", hi: "यह कान टैग किसी अन्य पशु के लिए पहले से प्रयुक्त है।" },
  // transport panel
  "cia.pur.vehicle": { en: "Vehicle number", hi: "वाहन संख्या" },
  "cia.pur.driver": { en: "Driver name", hi: "चालक का नाम" },
  "cia.pur.bill": { en: "Transport bill photo", hi: "परिवहन बिल फोटो" },
  "cia.pur.challan": { en: "Challan photo", hi: "चालान फोटो" },
  "cia.pur.take_photo": { en: "Take photo", hi: "फोटो लें" },
  "cia.pur.photo_done": { en: "photo taken", hi: "फोटो ली गई" },
  "cia.pur.save_step": { en: "Save", hi: "सहेजें" },
  "cia.pur.live_only": { en: "Live camera only — gallery disabled.", hi: "केवल लाइव कैमरा — गैलरी बंद।" },
  // post-capture phase
  "cia.pur.vet_pending": { en: "Vet verification pending", hi: "पशु चिकित्सक सत्यापन बाकी" },
  "cia.pur.vet_pending_sub": { en: "A veterinary officer will examine and value the animal, then approve the purchase.", hi: "पशु चिकित्सा अधिकारी पशु की जाँच व मूल्यांकन कर खरीद स्वीकृत करेंगे।" },
  "cia.pur.transit_title": { en: "Transit insurance", hi: "ट्रांज़िट बीमा" },
  "cia.pur.transit_sub": { en: "Covers the animal moving from the seller to your shed. Required before movement.", hi: "विक्रेता से आपके पशुशाला तक पशु को कवर करता है। परिवहन से पहले आवश्यक।" },
  "cia.pur.issue_transit": { en: "Issue transit policy", hi: "ट्रांज़िट पॉलिसी जारी करें" },
  "cia.pur.sum_insured": { en: "Sum insured (market value)", hi: "बीमित राशि (बाज़ार मूल्य)" },
  "cia.pur.arrival_title": { en: "Confirm arrival", hi: "आगमन की पुष्टि करें" },
  "cia.pur.arrival_sub": { en: "Confirm the animal has reached your shed.", hi: "पुष्टि करें कि पशु आपके पशुशाला पहुँच गया।" },
  "cia.pur.confirm_arrival": { en: "Confirm arrival at my shed", hi: "मेरे पशुशाला आगमन की पुष्टि करें" },
  "cia.pur.cattle_title": { en: "Cattle insurance", hi: "पशु बीमा" },
  "cia.pur.cattle_sub": { en: "Full policy assigned to the bank, effective from arrival. No backdating.", hi: "बैंक को निर्दिष्ट पूर्ण पॉलिसी, आगमन से प्रभावी। कोई बैकडेटिंग नहीं।" },
  "cia.pur.effective_date": { en: "Effective date", hi: "प्रभावी तिथि" },
  "cia.pur.issue_cattle": { en: "Issue cattle policy", hi: "पशु पॉलिसी जारी करें" },
  "cia.pur.backdated": { en: "Effective date cannot be before arrival (no backdated cover).", hi: "प्रभावी तिथि आगमन से पहले नहीं हो सकती (बैकडेटेड कवर नहीं)।" },
  "cia.pur.gate_pending": { en: "Payment under review", hi: "भुगतान समीक्षा में" },
  "cia.pur.gate_pending_sub": { en: "All evidence is in. The union verifies the traceability chain and recommends the seller payment — you'll be notified.", hi: "सभी साक्ष्य मिल गए। संघ ट्रेसबिलिटी शृंखला जाँचकर विक्रेता भुगतान की सिफारिश करेगा — आपको सूचित किया जाएगा।" },
  "cia.pur.paid_title": { en: "Seller paid", hi: "विक्रेता को भुगतान" },
  "cia.pur.paid_sub": { en: "The seller has been paid. Your milk-linked EMI begins — track it in your application.", hi: "विक्रेता को भुगतान हो गया। आपकी दूध-आधारित ईएमआई शुरू — आवेदन में देखें।" },
  "cia.pur.policy_no": { en: "Policy", hi: "पॉलिसी" },

  // ── milk-payment EMI ──
  "nav.cia_emi": { en: "Loan recovery", hi: "ऋण वसूली" },
  "nav.cia_emi_consent": { en: "Repayment authorisation", hi: "पुनर्भुगतान प्राधिकरण" },
  "cia.emi.as_of": { en: "As of yesterday's settlement file", hi: "कल की निपटान फ़ाइल के अनुसार" },
  "cia.emi.outstanding": { en: "outstanding", hi: "बकाया" },
  "cia.emi.next": { en: "next EMI", hi: "अगली ईएमआई" },
  "cia.emi.loan_ac": { en: "Loan a/c", hi: "ऋण खाता" },
  "cia.emi.mode_track": { en: "Track-only — deductions are read from the ERP. Set up authorisation to let the app initiate milk-payment deductions.", hi: "केवल ट्रैक — कटौती ईआरपी से पढ़ी जाती है। ऐप द्वारा दूध-भुगतान कटौती शुरू करने हेतु प्राधिकरण दें।" },
  "cia.emi.mode_initiate": { en: "Auto-deduction active — the EMI is deducted from your milk payment each month.", hi: "स्वतः कटौती सक्रिय — हर माह आपकी दूध राशि से ईएमआई काटी जाती है।" },
  "cia.emi.setup_consent": { en: "Set up auto-deduction", hi: "स्वतः कटौती सेट करें" },
  "cia.emi.manage_consent": { en: "Manage authorisation", hi: "प्राधिकरण प्रबंधित करें" },
  "cia.emi.deducted": { en: "deducted", hi: "कटौती" },
  "cia.emi.pending": { en: "pending", hi: "बकाया" },
  "cia.emi.nothing": { en: "nothing deducted", hi: "कोई कटौती नहीं" },
  "cia.emi.overdue_amt": { en: "overdue", hi: "अतिदेय" },
  "cia.emi.due": { en: "due", hi: "देय" },
  "cia.emi.moratorium": { en: "Moratorium — instalments due on or before", hi: "मोहलत — इस तिथि तक की किस्तें सुरक्षित:" },
  "cia.emi.no_schedule": { en: "Your repayment schedule will appear here once the loan is disbursed.", hi: "ऋण वितरण के बाद आपका पुनर्भुगतान कार्यक्रम यहाँ दिखेगा।" },
  "cia.emi.no_dues": { en: "Loan closed — view no-dues certificate", hi: "ऋण बंद — बकाया-रहित प्रमाण देखें" },
  "cia.emi.inst": { en: "Instalment", hi: "किस्त" },
  // status chips
  "cia.emi.st_paid": { en: "paid", hi: "चुकता" },
  "cia.emi.st_partial": { en: "partial", hi: "आंशिक" },
  "cia.emi.st_overdue": { en: "overdue", hi: "अतिदेय" },
  "cia.emi.st_due": { en: "due", hi: "देय" },
  "cia.emi.st_default": { en: "default", hi: "चूक" },
  "cia.emi.st_scheduled": { en: "scheduled", hi: "निर्धारित" },
  // consent screen
  "cia.emi.c_mode_track": { en: "Current mode: TRACK-ONLY (no consent on file)", hi: "वर्तमान मोड: केवल-ट्रैक (कोई सहमति नहीं)" },
  "cia.emi.c_mode_initiate": { en: "Current mode: AUTO-DEDUCT (consent active)", hi: "वर्तमान मोड: स्वतः-कटौती (सहमति सक्रिय)" },
  "cia.emi.c_you": { en: "You", hi: "आप" },
  "cia.emi.c_society": { en: "Society", hi: "समिति" },
  "cia.emi.c_bank": { en: "Bank", hi: "बैंक" },
  "cia.emi.c_pending_legal": { en: "The exact legal wording is being finalised with UCDF. This records your authorisation; the text below is indicative.", hi: "सटीक कानूनी शब्दावली यूसीडीएफ के साथ अंतिम की जा रही है। यह आपका प्राधिकरण दर्ज करता है; नीचे का पाठ सांकेतिक है।" },
  "cia.emi.c_head": { en: "You authorise, until you revoke:", hi: "आप प्राधिकृत करते हैं, जब तक रद्द न करें:" },
  "cia.emi.c_p1": { en: "your society and the co-op bank to deduct the monthly EMI from your milk payment,", hi: "आपकी समिति व सहकारी बैंक द्वारा आपकी दूध राशि से मासिक ईएमआई काटना," },
  "cia.emi.c_p2": { en: "the deduction to be remitted to your loan account,", hi: "कटौती आपके ऋण खाते में जमा करना," },
  "cia.emi.c_p3": { en: "deduction only up to the EMI due — any shortfall stays payable.", hi: "कटौती केवल देय ईएमआई तक — शेष राशि देय रहेगी।" },
  "cia.emi.c_dpdp": { en: "DPDP: consent is purpose-bound (emi_deduction), timestamped, and revocable anytime.", hi: "डीपीडीपी: सहमति उद्देश्य-बद्ध (emi_deduction), समय-मुद्रित व कभी भी रद्द करने योग्य।" },
  "cia.emi.c_checkbox": { en: "I have read and give this authorisation. I understand I can revoke it anytime.", hi: "मैंने पढ़ा और यह प्राधिकरण देता हूँ। मैं इसे कभी भी रद्द कर सकता हूँ।" },
  "cia.emi.c_give": { en: "Give consent", hi: "सहमति दें" },
  "cia.emi.c_revoke": { en: "Revoke consent", hi: "सहमति रद्द करें" },
  "cia.emi.c_given": { en: "Authorisation recorded", hi: "प्राधिकरण दर्ज हुआ" },
  "cia.emi.c_revoked": { en: "Authorisation withdrawn — recovery is track-only again.", hi: "प्राधिकरण वापस लिया — वसूली फिर केवल-ट्रैक।" },
  "cia.emi.c_stepup": { en: "Aadhaar verification is needed to authorise deductions.", hi: "कटौती प्राधिकृत करने हेतु आधार सत्यापन आवश्यक है।" },

  // ── loan & subsidy status ──
  "nav.cia_loan": { en: "Your loan", hi: "आपका ऋण" },
  "cia.loan.sanctioned": { en: "sanctioned", hi: "स्वीकृत" },
  "cia.loan.subsidy": { en: "Subsidy (govt share)", hi: "सब्सिडी (सरकारी अंश)" },
  "cia.loan.component": { en: "Bank loan component", hi: "बैंक ऋण भाग" },
  "cia.loan.contribution": { en: "Your contribution", hi: "आपका अंशदान" },
  "cia.loan.not_sanctioned": { en: "Your loan breakdown will appear here once the bank sanctions.", hi: "बैंक स्वीकृति के बाद आपका ऋण विवरण यहाँ दिखेगा।" },
  "cia.loan.start_purchase": { en: "Start cattle purchase", hi: "पशु खरीद शुरू करें" },
  "cia.loan.st_sanctioned": { en: "Loan sanctioned", hi: "ऋण स्वीकृत" },
  "cia.loan.st_subsidy": { en: "Subsidy transferred", hi: "सब्सिडी अंतरित" },
  "cia.loan.st_disbursed": { en: "Loan disbursed", hi: "ऋण वितरित" },
  "cia.loan.st_ready": { en: "Ready to buy cattle", hi: "पशु खरीदने हेतु तैयार" },
  "cia.loan.to_loan_ac": { en: "to your loan a/c", hi: "आपके ऋण खाते में" },
  "cia.loan.pending": { en: "pending", hi: "बाकी" },
  "cia.loan.details": { en: "Loan & subsidy details", hi: "ऋण व सब्सिडी विवरण" },

  // ── cattle claim ──
  "nav.cia_claim": { en: "Insurance claim", hi: "बीमा दावा" },
  "cia.claim.unavailable": { en: "A claim can be filed once your cattle is insured.", hi: "आपके पशु के बीमित होने पर दावा दायर किया जा सकता है।" },
  "cia.claim.report_title": { en: "Report death or loss", hi: "मृत्यु या हानि दर्ज करें" },
  "cia.claim.report_sub": { en: "File a claim against your cattle policy. Only 4 documents; settlement within 15 days of documents complete; 12% p.a. penal interest if the insurer is late.", hi: "अपनी पशु पॉलिसी पर दावा करें। केवल 4 दस्तावेज़; दस्तावेज़ पूर्ण होने के 15 दिनों में निपटान; बीमाकर्ता की देरी पर 12% प्रति वर्ष दंड ब्याज।" },
  "cia.claim.peril": { en: "What happened? (optional)", hi: "क्या हुआ? (वैकल्पिक)" },
  "cia.claim.peril_ph": { en: "e.g. illness, accident", hi: "जैसे बीमारी, दुर्घटना" },
  "cia.claim.sum": { en: "Amount claimed (optional)", hi: "दावा राशि (वैकल्पिक)" },
  "cia.claim.submit": { en: "File claim", hi: "दावा दर्ज करें" },
  "cia.claim.filed": { en: "Claim filed", hi: "दावा दर्ज हुआ" },
  "cia.claim.no_denial": { en: "No auto-denial — a human reviews every claim.", hi: "कोई स्वतः अस्वीकृति नहीं — हर दावे की मानव समीक्षा होती है।" },
  "cia.claim.clock": { en: "settlement clock (15 days from documents complete)", hi: "निपटान घड़ी (दस्तावेज़ पूर्ण होने से 15 दिन)" },
  "cia.claim.days_left": { en: "days left", hi: "दिन शेष" },
  "cia.claim.days_over": { en: "days overdue", hi: "दिन अतिदेय" },
  "cia.claim.settled": { en: "Settled", hi: "निपटाया गया" },
  "cia.claim.settled_amt": { en: "Settled amount", hi: "निपटान राशि" },
  "cia.claim.penal": { en: "Deadline breached — 12% p.a. penal interest accruing, added to your settlement:", hi: "समय-सीमा उल्लंघन — 12% प्रति वर्ष दंड ब्याज जुड़ रहा है, आपके निपटान में जोड़ा जाएगा:" },
  "cia.claim.docs": { en: "4 documents (only)", hi: "4 दस्तावेज़ (केवल)" },
  "cia.claim.progress": { en: "Progress", hi: "प्रगति" },
  "cia.claim.track": { en: "Track my claim", hi: "मेरा दावा देखें" },
  // claim stages
  "cia.claim.s_intimated": { en: "Intimated", hi: "सूचित" },
  "cia.claim.s_survey": { en: "Survey done", hi: "सर्वेक्षण पूर्ण" },
  "cia.claim.s_pm": { en: "Post-mortem", hi: "पोस्टमार्टम" },
  "cia.claim.s_docs": { en: "Documents submitted", hi: "दस्तावेज़ जमा" },
  "cia.claim.s_review": { en: "Under review", hi: "समीक्षाधीन" },
  "cia.claim.s_settled": { en: "Settled", hi: "निपटाया गया" },

  // ── shared ──
  "cia.web_capture_note": { en: "Camera & GPS capture run in the mobile app (a real device or simulator) — not this web preview.", hi: "कैमरा व जीपीएस कैप्चर मोबाइल ऐप (असली डिवाइस या सिम्युलेटर) में चलते हैं — इस वेब प्रीव्यू में नहीं।" },
  "cia.retry": { en: "Try again", hi: "पुनः प्रयास करें" },
  "cia.load_error": { en: "Couldn't load. Check your connection.", hi: "लोड नहीं हुआ। कनेक्शन जाँचें।" },
};
export default frag;
