/**
 * CiaBankBatch — a bank-wise packet generated by DUSS (checker) in the prescribed
 * format (the banker interface is a GENERATED DOCUMENT first — Convention 28).
 * In non-integrated mode the bank returns a sanction file against this batch.
 */
const { Model } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
  class CiaBankBatch extends Model {
    static associate(models) {
      if (models.CiaSanction) CiaBankBatch.hasMany(models.CiaSanction, { foreignKey: 'batch_id', as: 'sanctions' });
    }
  }
  CiaBankBatch.init({
    id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
    batch_uuid: { type: DataTypes.UUID, allowNull: false, unique: true },
    bank_ref: { type: DataTypes.STRING(40), allowNull: false },      // cooperative bank branch
    union_ref: { type: DataTypes.STRING(40), allowNull: false },     // DUSS that generated it
    application_ids: { type: DataTypes.JSONB, allowNull: false },    // members in this packet
    packet_doc_ref: { type: DataTypes.STRING(200), allowNull: true },// generated PDF/Excel (content-addressed)
    status: { type: DataTypes.STRING(24), allowNull: false, defaultValue: 'GENERATED' }, // GENERATED|SUBMITTED|SANCTION_RECEIVED
    generated_by_user_id: { type: DataTypes.INTEGER, allowNull: false },
    generated_at: { type: DataTypes.DATE, allowNull: false },
  }, {
    sequelize, modelName: 'CiaBankBatch', tableName: 'cia_bank_batches',
    timestamps: true, underscored: true,
  });
  return CiaBankBatch;
};
